from __future__ import annotations
import numpy
import typing

class MPOnlineSettings:
    max_opt_time: float
    hard_online_mode: bool
    opt_buffer: float

    def __init__(
        self,
        max_opt_time: float = 0.0,
        hard_online_mode: bool = False,
        opt_buffer: float = 0.0,
    ) -> None: ...

class JointData:
    @property
    def mirroring_logic(self) -> list[int]: ...
    @property
    def pos_min(self) -> list[float]: ...
    @property
    def pos_max(self) -> list[float]: ...
    @property
    def vel_max(self) -> list[float]: ...
    @property
    def acc_max(self) -> list[float]: ...
    @property
    def jerk_max(self) -> list[float]: ...
    def __init__(
        self,
        joint_mirroring: list[int],
        joint_pos_min: list[float],
        joint_pos_max: list[float],
        joint_vel_max: list[float],
        joint_acc_max: list[float],
        joint_jerk_max: list[float],
    ) -> None: ...

class ObjectiveFunction:
    """
    Members:
      magnitude
      difference
      mixed
    """

    __members__: typing.ClassVar[dict[str, ObjectiveFunction]]
    magnitude: typing.ClassVar[ObjectiveFunction]
    difference: typing.ClassVar[ObjectiveFunction]
    mixed: typing.ClassVar[ObjectiveFunction]

    def __eq__(self, other: typing.Any) -> bool: ...
    def __getstate__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __index__(self) -> int: ...
    def __init__(self, value: int) -> None: ...
    def __int__(self) -> int: ...
    def __ne__(self, other: typing.Any) -> bool: ...
    def __repr__(self) -> str: ...
    def __setstate__(self, state: int) -> None: ...
    def __str__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class CubicSpline:
    is_zero_tolerance: bool

    @staticmethod
    def get_solver_code_explanation(code: int) -> str: ...
    def __init__(
        self,
        tau_c: float,
        n_l: int,
        sampling_freq: int,
        n_joints: int,
        joint_data: JointData,
        online_settings: MPOnlineSettings,
        abstract_set_dim: int,
    ) -> None: ...
    def get_complete_ddu(self, joint_i: int) -> numpy.ndarray[numpy.float64]: ...
    def get_complete_du(self, joint_i: int) -> numpy.ndarray[numpy.float64]: ...
    def get_complete_u(self, joint_i: int) -> numpy.ndarray[numpy.float64]: ...
    def get_faoc_type(self) -> str: ...
    def is_mirroring_available(self) -> bool: ...
    def get_abstract_space_dimension(self) -> int: ...
    def get_joint_space_dimension(self) -> int: ...
    def get_fusion_index(self) -> int: ...
    def get_last_joint_action(self) -> numpy.ndarray[numpy.float64]: ...
    def get_last_joint_state(self) -> numpy.ndarray[numpy.float64]: ...
    def get_max_opt_cycles(self) -> int: ...
    def get_n_joints(self) -> int: ...
    def get_sampling_period(self) -> float: ...
    def get_step_size(self) -> int: ...
    def get_time_axis(self, joint_i: int, complete: bool) -> numpy.ndarray[numpy.float64]: ...
    def get_dddu_sol(self, joint_i: int) -> numpy.ndarray[numpy.float64]: ...
    def get_ddu_sol(self, joint_i: int) -> numpy.ndarray[numpy.float64]: ...
    def get_du_sol(self, joint_i: int) -> numpy.ndarray[numpy.float64]: ...
    def get_u_sol(self, joint_i: int) -> numpy.ndarray[numpy.float64]: ...
    def get_unique_centroid(self, joint_i: int) -> tuple[int, numpy.ndarray[numpy.float64]]: ...
    def get_max_controlled_invariant_set(self, joint_i: int) -> tuple[numpy.float64, numpy.float64]: ...
    def get_max_controlled_invariant_set_scaled(self, joint_i: int) -> tuple[numpy.float64, numpy.float64]: ...
    def get_reduced_position_limits(self) -> numpy.ndarray[numpy.float64]: ...
    def get_reduced_velocity_limits(self) -> numpy.ndarray[numpy.float64]: ...
    def get_reset_plan(
        self,
    ) -> tuple[
        numpy.ndarray[numpy.float64],
        numpy.ndarray[numpy.float64],
        numpy.ndarray[numpy.float64],
        numpy.ndarray[numpy.float64],
    ]: ...
    def get_position_limits(self) -> numpy.ndarray[numpy.float64]: ...
    def get_velocity_limits(self) -> numpy.ndarray[numpy.float64]: ...
    def get_acceleration_limits(self) -> numpy.ndarray[numpy.float64]: ...
    def initialize(self, obj_func: ObjectiveFunction, n_threads: int = 1) -> int: ...
    def initialize_reset_planner(
        self,
        p_reset_low: numpy.ndarray[numpy.float64],
        p_reset_up: numpy.ndarray[numpy.float64],
        mult: int = 2,
        add_steps: int = 0,
        n_threads: int = 1,
        max_n_l: int = 200,
        reset_sync: bool = False,
    ) -> int: ...
    def is_init(self) -> bool: ...
    def map_to_abstract_set(
        self, x_action: numpy.ndarray[numpy.float64]
    ) -> tuple[int, numpy.ndarray[numpy.float64]]: ...
    def map_from_abstract_set(self) -> int: ...
    def mirror_joint_state(self, x_state_or_action: numpy.ndarray[numpy.float64]) -> numpy.ndarray[numpy.float64]: ...
    def reset(self) -> None: ...
    def export_reset_plan_as_binary(self, export_fname: str) -> int: ...
    def set_abstract_action_and_solve(self, z_action: numpy.ndarray[numpy.float64]) -> int: ...
    def set_abstract_action(self, z_action: numpy.ndarray[numpy.float64]) -> int: ...
    def set_acceleration_limit_gain(self, a_gain: numpy.ndarray[numpy.float64]) -> int: ...
    def set_initial_state(self, x_0: numpy.ndarray[numpy.float64]) -> int: ...
    def check_state_in_invariant_set(self, x_0: numpy.ndarray[numpy.float64]) -> numpy.ndarray[numpy.int64]: ...
    def compute_reset_trajectory(
        self,
        current_state: numpy.ndarray[numpy.float64],
        reset_pos: numpy.ndarray[numpy.float64],
    ) -> int: ...
    def set_velocity_limit_gain(self, v_gain: numpy.ndarray[numpy.float64]) -> int: ...
    def set_jerk_limit_gain(self, j_gain: numpy.ndarray[numpy.float64]) -> int: ...
    def set_tolerances(self, p_tol: numpy.ndarray[numpy.float64], v_tol: numpy.ndarray[numpy.float64]) -> int: ...
    def solve(self) -> int: ...
